
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'

name: build-test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-
    - run: go env
    - name: go build
      run: go build -v ./...
    - name: go test
      run: go test -v ./...
    - name: build lord
      run: go build -o lord -v .
    - name: Upload lord binary
      uses: actions/upload-artifact@v3
      with:
        name: lord-bin
        path: lord

  test-tekton:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v3
      with:
        name: lord-bin
    - uses: chainguard-dev/actions/setup-kind@main
      with:
        k8s-version: v1.24.x
    - name: generate and start a simple task
      run: |
        chmod +x ./lord
        ./lord generate tekton-task -f ./tests/simple-go/lord.yaml lord
        ./lord generate tekton-task -f ./tests/simple-go/lord.yaml tkn
  test-docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v3
      with:
        name: lord-bin
    - name: generate and build a simple dockerfile
      run: |
        chmod +x ./lord
        ./lord generate dockerfile -f ./tests/simple-go/lord.yaml lord | docker build -f - .
        ./lord generate dockerfile -f ./tests/simple-go/lord.yaml tkn | docker build -f - https://github.com/tektoncd/cli.git#main
